name: Task
description: Конкретна задача към дадена стъпка
labels: ["type:task", "status:todo"]
body:
  - type: input
    id: scope
    attributes:
      label: Scope
      placeholder: "CLI roundtrip test covers unwrap errors"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: "pytest passes; error mapped to ForitechError"
    validations:
      required: true
