name: CI • Lite (lint + discover)
on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: lite-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install ruff
      - run: ruff version && ruff check .
  discover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install -e ".[dev]"
      - run: python - <<'PY'
              import importlib
              m = importlib.import_module("foritech")
              import foritech.cli.main as cli
              print("foritech loaded:", getattr(m, "__file__", "<no file>"))
              print("cli OK")
              PY
      - run: foritech --help

      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          # инсталираме lib-а от папка sdk (editable), + pytest и cryptography
          pip install -e sdk
          pip install pytest cryptography

      - name: Run tests
        env:
          PYTHONPATH: sdk/src
        run: pytest -q
