name: CI

on:
  push:
  pull_request:

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git build-essential cmake ninja-build libssl-dev

      - name: Build & install liboqs (Dilithium only)
        run: |
          git clone --depth=1 https://github.com/open-quantum-safe/liboqs.git
          mkdir -p liboqs/build
          cd liboqs/build
          cmake -GNinja -DCMAKE_INSTALL_PREFIX=/usr/local -DOQS_USE_OPENSSL=OFF \
                -DOQS_BUILD_ONLY_LIB=ON \
                -DOQS_ENABLE_KEM=OFF \
                -DOQS_ENABLE_SIG=ON \
                -DOQS_ENABLE_SIG_dilithium=ON \
                -DOQS_ENABLE_SIG_falcon=OFF \
                -DOQS_ENABLE_SIG_mldsa=OFF
          ninja
          sudo ninja install
          sudo ldconfig

      - name: Build & install liboqs-python (oqs)
        run: |
          git clone --depth=1 https://github.com/open-quantum-safe/liboqs-python.git
          cd liboqs-python
          python -m pip install -U pip wheel setuptools
          python -m pip install .

      - name: Install SDK (editable + dev)
        working-directory: sdk
        run: |
          python -m pip install -e .[dev]

      - name: Run tests
        working-directory: sdk
        run: |
          pytest -q

