name: Coverage Badge

on:
  push:
    branches: [ main, chore/pqc-starter-import ]
  pull_request:
    branches: [ main, chore/pqc-starter-import ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build liboqs (shared)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build libssl-dev
          git clone --depth=1 https://github.com/open-quantum-safe/liboqs.git
          cmake -S liboqs -B liboqs/build -G Ninja -DOQS_BUILD_ONLY_LIB=ON -DBUILD_SHARED_LIBS=ON -DOQS_USE_OPENSSL=OFF
          cmake --build liboqs/build --config Release
          sudo cmake --install liboqs/build
          echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/oqs.conf
          sudo ldconfig

      - name: Install deps (editable SDK + tests)
        run: |
          python -m pip install -U pip
          python -m pip install -e sdk
          python -m pip install pytest pytest-cov pycryptodome jq

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}/sdk/src
        run: |
          pytest --maxfail=1 --disable-warnings -q \
            --cov=foritech --cov-report=term-missing \
            --cov-report=html --cov-report=json:coverage.json

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

      - name: Upload coverage JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-json
          path: coverage.json
