name: Coverage Badge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # ако имате requirements:
          if [ -f sdk/requirements.txt ]; then pip install -r sdk/requirements.txt; fi
          pip install pytest coverage coverage-badge
          # инсталирайте SDK-то, ако е пакетируемо (не е фатално ако не е)
          if [ -f sdk/pyproject.toml ] || [ -f sdk/setup.py ]; then pip install -e sdk || true; fi

      - name: Run tests with coverage
        working-directory: sdk
        run: |
          coverage run -m pytest -q
          coverage xml
          coverage report

      - name: Generate badge
        working-directory: sdk
        run: |
          coverage-badge -o coverage.svg -f

      - name: Collect badge
        run: |
          mkdir -p .github/badges
          cp sdk/coverage.svg .github/badges/coverage.svg

      - name: Upload badge artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: .github/badges/coverage.svg

      # Комитва/ъпдейтва баджа само при push към main (не при PR)
      - name: Commit badge to repo (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if [[ -n "$(git status --porcelain .github/badges/coverage.svg)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .github/badges/coverage.svg
            git commit -m "docs: update coverage badge [skip ci]" || true
            git push
          fi
