name: Nightly Progress Snapshot

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'
  schedule:
    - cron: "5 0 * * *"  # ежедневно 00:05 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update PROGRESS.md
        run: |
          python scripts/update_progress.py

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add PROGRESS.md
            git commit -m "chore(progress): nightly snapshot"
            git push
          fi
