name: Release ZIP (docs)
on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          set -euo pipefail
          VERSION="${GITHUB_REF_NAME:-manual}"
          mkdir -p dist
          # включваме само документацията + лиценз/README
          zip -r "dist/foritech-secure-system-docs-${VERSION}.zip" docs README.md LICENSE || true
          echo "ZIP_PATH=dist/foritech-secure-system-docs-${VERSION}.zip" >> $GITHUB_ENV
          ls -lh dist

      - name: Upload artifact (manual runs)
        if: ${{ github.event_name != 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: docs-zip
          path: ${{ env.ZIP_PATH }}

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_PATH }}
          draft: false
          prerelease: false
          generate_release_notes: true
