name: CI • Full (liboqs + tests)

on:
  push:
    branches: [ "main", "chore/**", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      FORITECH_TEST_KEM: Kyber768
      PYTHONPATH: ${{ github.workspace }}/sdk/src
      LD_LIBRARY_PATH: /usr/local/lib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          # core deps
          python -m pip install pytest pyoqs
          # project deps (if present)
          if [ -f sdk/requirements.txt ]; then pip install -r sdk/requirements.txt; fi
          pip install -e sdk || true

      - name: Verify oqs
        run: |
          python - <<'PY'
          import oqs, sys
          print("oqs version OK")
          print("enabled KEMs:", len(getattr(oqs, "get_enabled_kem_mechanisms", lambda: [])()))
          PY

      - name: Run tests (verbose)
        run: |
          python -m pytest -vv
