name: Tests (full)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "chore/**", "feature/**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f sdk/requirements.txt ]; then pip install -r sdk/requirements.txt; fi
          pip install -e sdk || true
          pip install pytest

      - name: Run tests (verbose)
        run: |
          pytest -vv
