name: CI • Full (liboqs + tests)

on:
  push:
    branches: [ "main", "chore/**", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      FORITECH_TEST_KEM: Kyber768          # ползваш го вече в теста
      LD_LIBRARY_PATH: /usr/local/lib
      PYTHONPATH: ${{ github.workspace }}/sdk/src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Apt dependencies (oqs)
        run: |
          sudo apt-get update
          # ако имаш собствен начин за oqs/openssl oqs-provider, добави го тук
          # оставяме стъпката като hook; tests, които не зависят, ще минат и без него
          true

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f sdk/requirements.txt ]; then pip install -r sdk/requirements.txt; fi
          pip install -e sdk || true
          pip install pytest

      - name: Run tests (verbose)
        run: |
          pytest -vv
