name: CI • Debug one test

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ "main" ]

jobs:
  debug-one:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORITECH_TEST_KEM: Kyber768
      PYTHONPATH: ${{ github.workspace }}/sdk/src

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pyoqs
          pip install -e sdk || true

      - name: Run only the hybrid CLI roundtrip test (verbose)
        run: |
          pytest -vv -s sdk/tests/test_cli_hybrid.py::test_cli_wrap_unwrap_roundtrip
