name: CI • Full (liboqs + tests)

on:
  push:
    branches: [ "main", "chore/**", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      FORITECH_TEST_KEM: Kyber768
      PYTHONPATH: ${{ github.workspace }}/sdk/src
      LD_LIBRARY_PATH: /usr/local/lib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python deps (pytest + oqs)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          # Опитай първо 'oqs', ако няма колело – fallback към 'pyoqs'
          python -m pip install oqs || python -m pip install pyoqs || true
          # проектни зависимости (ако съществуват)
          if [ -f sdk/requirements.txt ]; then pip install -r sdk/requirements.txt; fi
          pip install -e sdk || true

      - name: Verify oqs import (optional)
        shell: python
        continue-on-error: true
        run: |
          import importlib, sys
          m = importlib.import_module("oqs")
          print("oqs imported OK:", m.__name__)

      - name: Run tests (verbose)
        run: |
          python -m pytest -vv
