name: Update PROGRESS.md on main

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate compressed progress section
        run: |
          python scripts/update_progress.py

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add PROGRESS.md
            git commit -m "chore(progress): auto-update PROGRESS.md"
            git push
          fi
